steps:
  #Step 1: Build Docker image (with optional no-cache)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile

  #Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  #Step 3: Deploy to Cloud Run with controlled env vars
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --set-env-vars=GCP_PROJECT_ID=$_AR_PROJECT_ID,
        GCP_RAG_CORPUS_REGION=$_RAG_CORPUS_REGION,
        GCP_RAG_CORPUS_ID=$_RAG_CORPUS_ID,
        GCP_GEMINI_REGION=$_GEMINI_REGION,
        GCP_BQ_DATASET_ID=$_BQ_DATASET_ID,
        GCP_BQ_TABLE_ID=$_BQ_TABLE_ID,
        QUERY_REWRITE_STRATEGY=sub_query,

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

